---
- name: Play | Ansible Docker Media Stack
  hosts: all
  become: true

  tasks:
    - name: Include the geerlingguy.repo-epel role for Redhat
      ansible.builtin.include_role:
        name: geerlingguy.repo-epel
      when: ansible_os_family == 'Redhat'

    - name: Include the geerlingguy.pip role
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: Include the geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Include the docker-container role
      ansible.builtin.include_role:
        name: docker-container
