---
- name: "Check if snap is installed"
  package_facts:
    manager: apt

- name: Remove snap functionality
  when: ("'snapd' in ansible_facts.packages") and (not enable_snap | default(false))
  block:
  - name: "Disable Snapd Service"
    ansible.builtin.service:
      name: snapd
      state: stopped
      enabled: false

  - name: "Uninstall Snapd"
    ansible.builtin.apt:
      pkg: snapd
      state: absent
